Repository ita-social-projects/EPlast-Client, pull requests merged in 2020-07, with the labels that each got.

#7 VV user profile connection
  .eslintrc.js
  .vscode/launch.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/api/UserApi.tsx
  src/api/api.ts
  src/assets/images/avatar.jpg
  src/assets/images/default_user_image.png
  src/pages/userPage/EditUserPage/EditUserPage.module.css
  src/pages/userPage/EditUserPage/EditUserPage.tsx
  src/pages/userPage/EditUserPage/Interface.tsx
  src/pages/userPage/Menu/Menu.tsx
  src/pages/userPage/personalData/AvatarAndProgress.tsx
  src/pages/userPage/personalData/UserFields.tsx
Labels: enhancement

#8 AS-Add chat component
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/authorizeApi.ts
  src/api/contactsApi.ts
  src/index.tsx
  src/pages/Actions/ActionEvent/SortedEvents.tsx
  src/pages/ChangePassword/ChangePassword.tsx
  src/pages/DecisionTable/DecisionTable.jsx
  src/pages/ForgotPassword/ForgotPassword.tsx
  src/pages/ResetPassword/ResetPassword.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/WebChat/Demo.js
  src/pages/userPage/personalData/UserFields.tsx
Labels: help wanted

#11 Decision binding
  .vscode/launch.json
  package-lock.json
  src/api/UserApi.tsx
  src/api/api.ts
  src/api/authorizeApi.ts
  src/api/decisionsApi.tsx
  src/components/PrivateLayout/PrivateLayout.tsx
  src/config.ts
  src/pages/ActionCard/ActionCard.tsx
  src/pages/Actions/ActionEvent/ActionEvent.tsx
  src/pages/Actions/ActionEvent/EventCard/EventCard.tsx
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/Gallery.tsx
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/data.tsx
  src/pages/Actions/ActionEvent/SortedEvents.tsx
  src/pages/Actions/Actions.tsx
  src/pages/DecisionTable/AddDecisionModal.jsx
  src/pages/DecisionTable/AddDecisionModal.tsx
  src/pages/DecisionTable/DecisionTable.tsx
  src/pages/DecisionTable/DeleteConfirm.jsx
  src/pages/DecisionTable/DeleteConfirm.tsx
  src/pages/DecisionTable/DropDownDecision.jsx
  src/pages/DecisionTable/DropDownDecision.tsx
  src/pages/DecisionTable/EditDecisionModal.jsx
  src/pages/DecisionTable/EditDecisionModal.tsx
  src/pages/DecisionTable/FormAddDecision.jsx
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/DecisionTable/FormEditDecision.jsx
  src/pages/DecisionTable/FormEditDecision.tsx
  src/pages/DecisionTable/Table.module.css
  src/pages/DecisionTable/columns.jsx
  src/pages/DecisionTable/columns.tsx
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUp/Switcher/Switcher.tsx
  src/pages/SignUp/verification.ts
  src/pages/userPage/EditUserPage/Services.tsx
  src/pages/userPage/Menu/Menu.module.css
  src/pages/userPage/Menu/Menu.tsx
  src/pages/userPage/personalData/EditEvent/EditEvent.module.css
  src/pages/userPage/personalData/EditEvent/EditEvent.tsx
  src/pages/userPage/personalData/PersonalData.module.css
  src/pages/userPage/personalData/PersonalData.tsx
  src/pages/userPage/personalData/UserFields.tsx
Labels: enhancement

#13 adding notifications for decisions/refactoring decisions components
  src/api/decisionsApi.tsx
  src/pages/DecisionTable/DecisionTable.tsx
  src/pages/DecisionTable/DeleteConfirm.tsx
  src/pages/DecisionTable/DropDownDecision.tsx
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/DecisionTable/FormEditDecision.tsx
  src/pages/DecisionTable/columns.tsx
Labels: enhancement

#16 As add changes and fixed problems
  src/api/api.ts
  src/api/authorizeApi.ts
  src/api/contactsApi.ts
  src/components/Header/HeaderContainer.tsx
  src/components/PrivateLayout/PrivateLayout.tsx
  src/config.ts
  src/index.tsx
  src/pages/ChangePassword/ChangePassword.tsx
  src/pages/Contacts/Contacts.tsx
  src/pages/ForgotPassword/ForgotPassword.tsx
  src/pages/SignUp/SignUp.tsx
  src/pages/userPage/personalData/UserFields.tsx
Labels: bug, enhancement

#34 VV Approvers page
  src/App.tsx
  src/api/UserApi.tsx
  src/assets/images/no-avatar.png
  src/assets/images/user_add.png
  src/components/Header/HeaderContainer.tsx
  src/config.ts
  src/pages/SignIn/SignIn.tsx
  src/pages/userPage/Approvers/Approvers.module.css
  src/pages/userPage/Approvers/Approvers.tsx
  src/pages/userPage/EditUserPage/EditUserPage.tsx
  src/pages/userPage/Interface/Interface.tsx
  src/pages/userPage/Menu/Menu.tsx
  src/pages/userPage/personalData/PersonalData.tsx
  src/pages/userPage/personalData/UserFields.tsx
Labels: enhancement

#36 Decision creating
  src/api/decisionsApi.tsx
  src/pages/DecisionTable/AddDecisionModal.tsx
  src/pages/DecisionTable/DecisionTable.tsx
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/DecisionTable/Table.module.css
Labels: enhancement

#37 Change 'moment' library
  src/pages/userPage/Approvers/Approvers.tsx
Labels: bug
