Repository ita-social-projects/EPlast-Client, pull requests merged in 2020-08, with the labels that each got.

#44 AS-Fix problem with Authorization
  src/api/api.ts
  src/api/authorizeApi.ts
  src/components/Header/HeaderContainer.tsx
  src/components/PrivateLayout/PrivateLayout.tsx
  src/pages/Actions/ActionEvent/EventUser/EventUser.tsx
  src/pages/ChangePassword/ChangePassword.module.css
  src/pages/ChangePassword/ChangePassword.tsx
  src/pages/ForgotPassword/ForgotPassword.module.css
  src/pages/ForgotPassword/ForgotPassword.tsx
  src/pages/ResetPassword/ResetPassword.module.css
  src/pages/ResetPassword/ResetPassword.tsx
  src/pages/SignIn/SignIn.module.css
  src/pages/SignIn/SignIn.tsx
  src/pages/SignUp/SignUp.module.css
  src/pages/SignUp/SignUp.tsx
  src/pages/SignUp/Switcher/Switcher.module.css
  src/pages/userPage/Approvers/Approvers.tsx
  src/pages/userPage/EditUserPage/EditUserPage.tsx
  src/pages/userPage/Menu/Menu.tsx
  src/stores/Auth.ts
  src/stores/AuthStore.ts
Labels: bug, good first issue

#48 Br events binding
  src/api/eventsApi.ts
  src/assets/images/ActionLogo.png
  src/assets/images/EventGallary(1).jpg
  src/assets/images/EventGallary(2).jpg
  src/assets/images/EventGallary(3).jpg
  src/assets/images/handshake.png
  src/pages/ActionCard/ActionCard.tsx
  src/pages/Actions/ActionEvent/EventCard/EventCard.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.module.css
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx
  src/pages/Actions/ActionEvent/EventInfo/Gallery.tsx
  src/pages/Actions/ActionEvent/EventInfo/GalleryNotifications.tsx
  src/pages/Actions/ActionEvent/EventInfo/PicturesWall.tsx
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
  src/pages/Actions/ActionEvent/SortedEvents.tsx
  src/pages/Actions/Actions.tsx
  src/pages/Actions/EventTypes/EventTypeCard.tsx
  src/pages/Actions/EventTypes/EventTypes.tsx
  src/pages/Actions/EventsModals.tsx
Labels: enhancement

#53 fixed pdf bug
  src/pages/DecisionTable/DropDownDecision.tsx
Labels: bug

#59 VV responsive
  src/pages/userPage/Approvers/Approvers.less
  src/pages/userPage/Approvers/Approvers.tsx
  src/pages/userPage/EditUserPage/EditUserPage.module.css
  src/pages/userPage/Menu/Menu.less
  src/pages/userPage/Menu/Menu.module.css
  src/pages/userPage/Menu/Menu.tsx
  src/pages/userPage/personalData/AvatarAndProgress.tsx
  src/pages/userPage/personalData/PersonalData.less
  src/pages/userPage/personalData/PersonalData.module.css
  src/pages/userPage/personalData/PersonalData.tsx
  src/pages/userPage/personalData/UserFields.tsx
Labels: enhancement

#63 Fix styles
  src/pages/userPage/Approvers/Approvers.less
Labels: bug

#68 Added Dockerfile
  .dockerignore
  Dockerfile
  nginx/nginx.conf
Labels: Configuration

#78 VV fix bugs
  src/api/authorizeApi.ts
  src/pages/userPage/Approvers/Approvers.less
  src/pages/userPage/Approvers/Approvers.tsx
  src/pages/userPage/EditUserPage/EditUserPage.module.css
  src/pages/userPage/EditUserPage/EditUserPage.tsx
  src/pages/userPage/personalData/AvatarAndProgress.tsx
  src/pages/userPage/personalData/PersonalData.less
  src/pages/userPage/personalData/UserFields.tsx
Labels: enhancement

#87 Br event details improvements
  src/api/eventsApi.ts
  src/assets/images/EventAdmin.png
  src/config.ts
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.module.css
  src/pages/Actions/ActionEvent/EventInfo/EventDetails.less
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.module.css
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx
  src/pages/Actions/ActionEvent/EventInfo/Gallery.tsx
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.less
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.module.css
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
  src/pages/Actions/ActionEvent/EventInfo/PicturesWall.tsx
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
Labels: Status: Completed, Type: Enhancement

#97 Plast degrees
  src/api/activeMembershipApi.ts
  src/config.ts
  src/pages/userPage/ActiveMembership/ActiveMembership.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
Labels: Configuration, enhancement
