Repository ita-social-projects/EPlast-Client, pull requests merged in 2021-06, with the labels that each got.

#383 Changed progress bar
  src/pages/userPage/personalData/AvatarAndProgress.tsx
  src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
Labels: Type: Bug

#386 Governing body Administration
  src/App.tsx
  src/models/GoverningBody/GoverningBodyAdmin.tsx
  src/models/GoverningBody/GoverningBodyProfile.tsx
  src/pages/Documents/FormAddDocument.tsx
  src/pages/GoverningBody/AddAdministratorModal/AddAdministrationModal.less
  src/pages/GoverningBody/AddAdministratorModal/AddAdministratorModal.tsx
  src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
  src/pages/GoverningBody/CreateGoverningBody.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.less
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.module.css
  src/pages/GoverningBody/GoverningBody/GoverningBodyAdministration.tsx
  src/pages/UserTable/ColumnsForUserTable.tsx
  src/pages/userPage/ActiveMembership/ActiveMembership.tsx
  src/pages/userPage/Approvers/Approvers.less
  src/pages/userPage/Approvers/Approvers.tsx
Labels: Governing bodies

#392 Governing body documents
  src/App.tsx
  src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
  src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.less
  src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBodyDocuments.tsx
  src/pages/RegionsBoard/RegionBoard.tsx
  src/pages/RegionsBoard/RegionBoardDocuments.tsx
Labels: Governing bodies

#389 Add user in admins
  src/api/regionsApi.tsx
  src/models/Region/RegionUser.tsx
  src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx
  src/pages/City/City/CityAdministration.tsx
  src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx
  src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx
  src/pages/Club/Club/ClubAdministration.tsx
  src/pages/Regions/AddRegionSecretaryForm.tsx
  src/pages/Regions/Region.tsx
  src/pages/Regions/RegionAdministration.tsx
Labels: City, Clubs, Regions

#396 Add creat clubs and display users in when added by the administrator
  src/models/Club/ClubUser.tsx
  src/pages/City/City/City.tsx
  src/pages/City/City/CityMembers.tsx
  src/pages/Club/Club/Club.tsx
  src/pages/Club/Club/ClubMembers.tsx
Labels: City, Clubs

#394 Change password
  src/pages/ChangePassword/ChangePassword.module.css
  src/pages/ChangePassword/ChangePassword.tsx
Labels: Type: Bug

#393 Fix of access levels on regions and cities (actual)
  src/api/UserApi.tsx
  src/pages/City/City/City.tsx
  src/pages/City/City/CityAdministration.tsx
  src/pages/City/City/CityDocuments.tsx
  src/pages/City/City/CityFollowers.tsx
  src/pages/City/City/CityMembers.tsx
  src/pages/Regions/Region.tsx
  src/pages/Regions/RegionAdministration.tsx
  src/pages/Regions/RegionDocuments.tsx
Labels: City, Regions

#401 Fixed Incorrect error message appears #1051
  src/components/Notifications/Messages.tsx
  src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
Labels: Awards (Відзначення), Type: Bug

#399 Fixed Spelling mistakes on the Home page #1340
  src/pages/Home/Home.tsx
Labels: Type: Bug, UI

#402 Fixed [City/Станиця] and [Hovel/Курінь] 2 notifications appear while …
  src/pages/City/CreateCity/CreateCity.tsx
  src/pages/Club/CreateClub/CreateClub.tsx
Labels: Cities (Станиці), Hovels (Курені), Type: Bug

#400 Fix bug with post index field in stanytsia creation form
  src/models/GllobalValidations/DescriptionValidation.tsx
Labels: City, UI

#404 Removed (hidden) link on Documents section #1329
  src/pages/City/City/City.less
  src/pages/City/City/City.tsx
  src/pages/Club/Club/Club.less
  src/pages/Club/Club/Club.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.less
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/Regions/Region.less
  src/pages/Regions/Region.tsx
  src/pages/RegionsBoard/RegionBoard.tsx
Labels: Type: Bug, documentation

#405 Fix Menu
  src/components/PrivateLayout/PrivateLayout.tsx
  src/components/PrivateLayout/useOneClickOutside.tsx
Labels: Status: Completed

#407 Made NotificationBox responsible for phones.
  src/components/NotificationBox/NotificationBox.less
  src/components/NotificationBox/NotificationBox.tsx
Labels: Type: Bug, UI

#409 Fixed some bugs for access levels on the region documents
  src/pages/Regions/Region.tsx
  src/pages/Regions/RegionDocuments.tsx
Labels: Regions, Type: Bug

#408 Fixed on Event page text fonts and styles #1353
  src/pages/Actions/ActionEvent/EventInfo/EventDetails.less
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/Actions/Actions.module.css
Labels: Events, Type: Bug, UI

#411 Fixed a mismatch in JoinCity and JoinHovel #1356
  src/pages/City/City/City.tsx
  src/pages/Club/Club/Club.tsx
Labels: Cities (Станиці), Clubs, UI

#413 Improved document sections
  src/components/Notifications/Messages.tsx
  src/pages/City/City/City.tsx
  src/pages/Club/AddDocumentModal/AddDocumentModal.tsx
  src/pages/Regions/AddDocModal.tsx
  src/pages/Regions/Region.tsx
  src/pages/userPage/Blanks/Blanks.module.css
Labels: City, Region, UI
