Repository ita-social-projects/EPlast-Client, pull requests merged in 2021-12, with the labels that each got.

#741 Fixed buttons on events and calendar#1698
  src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.module.css
  src/pages/Actions/ActionEvent/EventUser/EventUser.module.css
  src/pages/Actions/ActionEvent/EventUser/EventUser.tsx
Labels: Type: Bug, Events

#746 fixed selecting users in event creation #1925
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
Labels: Type: Bug, Events

#745 added notifications when changing participation status in event #2080
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
  src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
Labels: Notifications(Сповіщення), Events

#748 fixed date entry error
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/Documents/FormAddDocument.tsx
  src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx
  src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx
Labels: Type: Bug, Legislation [Репозитарій], Decisions (Рішення), Repository, Senior Staff (Кадра виховників)

#740 Fixed event galary and event description #1989
  src/pages/Actions/ActionEvent/EventInfo/EventDetails.less
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
  src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx
  src/pages/Actions/ActionEvent/EventInfo/Gallery.tsx
Labels: Type: Bug, Events

#747 add new setAdmins
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx
  src/pages/City/City/City.tsx
  src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx
  src/pages/Club/Club/Club.tsx
  src/pages/Regions/AddRegionSecretaryForm.tsx
  src/pages/Regions/Region.tsx
Labels: Regions, Cities (Станиці), Hovels (Курені)

#753 Accesses for editing event
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
  src/pages/Actions/ActionEvent/EventUser/EventUser.tsx
Labels: Type: Bug, Events

#754 Added API function and proper type for EducatorsStaff table (partially covers issue #2117)
  src/api/KadraVykhovnykivApi.tsx
  src/pages/KadraVykhovnykiv/Types/EducatorsStaffTableData.ts
Labels: Senior Staff (Кадра виховників)

#749 Delete yourself bug fixed
  src/api/citiesApi.tsx
  src/api/clubsApi.tsx
  src/pages/City/City/City.tsx
  src/pages/Club/Club/Club.tsx
  src/pages/Regions/Region.tsx
Labels: Cities (Станиці), Hovels (Курені)

#755 made admin card clickable
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
Labels: Events

#738 User annual report statistics update
  src/api/AnnualReportApi.tsx
  src/api/StatisticsApi.tsx
  src/components/PrivateLayout/PrivateLayout.tsx
  src/models/AnnualReport/ReportType.ts
  src/models/UserAccess/IUserAccess.ts
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
  src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx
  src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/SavedDropdown/SavedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/SavedDropdown/SavedRegionDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdownProps.tsx
  src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
Labels: Statistics, Рівні доступу (Access levels), AnnualReports

#750 fixed loading on switching between tabs
  src/pages/KadraVykhovnykiv/Interfaces/KadraTableInfo.tsx
  src/pages/KadraVykhovnykiv/KVTable.tsx
  src/pages/KadraVykhovnykiv/Table.module.css
  src/pages/KadraVykhovnykiv/columns.tsx
Labels: Senior Staff (Кадра виховників)

#757 Changed messages in notifications after confirm or cancel annual report
  src/components/Notifications/Messages.tsx
  src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx
  src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx
Labels: AnnualReports

#759 fixed deleting decision
  src/pages/DecisionTable/DecisionTable.tsx
Labels: Decisions (Рішення)

#761 Fix error massage bag
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/City/CreateCity/CreateCity.tsx
  src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
  src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx
  src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx
  src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx
  src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
  src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
  src/pages/Precaution/PrecautionTable/columns.tsx
  src/pages/Regions/AddRegion.tsx
  src/pages/Regions/RegionEdit.tsx
Labels: Regions, Precaution, Awards (Відзначення), Cities (Станиці), Distinctions, Senior Staff (Кадра виховників)

#763 Terms
  package-lock.json
  package.json
  src/App.tsx
  src/api/termsApi.tsx
  src/components/PrivateLayout/PrivateLayout.tsx
  src/models/TermsOfUse/TermsOfUseModel.tsx
  src/pages/Terms/TermsEdit.tsx
  src/pages/Terms/TermsOfUse.less
  src/pages/Terms/TermsOfUse.tsx
Labels: Terms

#764 Add modal confirm for agreement with terms
  src/pages/SignUp/SignUp.tsx
Labels: Terms

#751 Removed Option Зареєстрований користувач for all Members except for F…
  src/pages/UserTable/ChangeUserRoleForm.tsx
Labels: Type: Bug, Рівні доступу (Access levels)

#765 Added tip for mention
  src/pages/DecisionTable/FormAddDecision.tsx
Labels: Decisions (Рішення)

#767 Fix event dates
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
  src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/Actions/ActionEvent/EventUser/EventUser.tsx
Labels: Events

#768 Add About base icon
  src/components/PrivateLayout/PrivateLayout.tsx
Labels: About base

#766 edit SetPhoto and delete CanCreate
  src/pages/City/Cities/SortedCities.tsx
Labels: Cities (Станиці)

#758 added arrows to galary carousel and fixed button upload photo
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
  src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx
  src/pages/Actions/ActionEvent/EventInfo/Gallery.tsx
  src/pages/Actions/ActionEvent/EventInfo/PicturesWall.tsx
Labels: Type: Bug, Events

#771 Fixed agreement terms
  src/pages/SignUp/SignUp.tsx
Labels: Terms

#772 Fixed that modal menu was out screen and mobile bug #2020
  src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx
  src/pages/AnnualReport/AnnualReportTable/CitySelectModal/CitySelectModal.less
  src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/SavedDropdown/SavedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
Labels: Type: Bug, AnnualReports

#774 Changed club pagination
  src/models/Club/ClubByPage.tsx
  src/pages/Club/Clubs/SortedClubs.tsx
Labels: Hovels (Курені)

#775 fixed the date entry bug
  src/api/decisionsApi.tsx
  src/models/Documents/DocumentPost.tsx
  src/models/Documents/DocumentsTableInfo.tsx
  src/pages/DecisionTable/DropDownDecision.tsx
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/DecisionTable/Interfaces/DecisionTableInfo.tsx
  src/pages/Documents/DropDownDocuments.tsx
  src/pages/Documents/FormAddDocument.tsx
  src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx
Labels: Type: Bug, Legislation [Репозитарій], Decisions (Рішення), Senior Staff (Кадра виховників)

#776 Fixed sign in and sign up buttons (fixes bug #1758)
  src/pages/SignUp/Switcher/Switcher.module.css
Labels: UI

#777 fixed access for club edit page
  src/models/AnnualReport/ReportStatus.ts
  src/models/AnnualReport/ReportType.ts
  src/pages/AnnualReport/ClubAnnualReportEdit/ClubAnnualReportEdit.tsx
Labels: Рівні доступу (Access levels), AnnualReports

#778 Fixed modal confirm with terms
  src/pages/SignUp/SignUp.tsx
Labels: UI, Terms

#779 fixed the date entry bug
  src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx
Labels: Type: Bug, Senior Staff (Кадра виховників)

#752 User profile access (Fixes bugs #1964 #1948 #2042)
  src/api/UserApi.tsx
  src/pages/userPage/ActiveMembership/ActiveMembership.tsx
  src/pages/userPage/Approvers/Approvers.tsx
  src/pages/userPage/Blanks/Blanks.tsx
  src/pages/userPage/EditUserPage/EditUserPage.tsx
  src/pages/userPage/Interface/Interface.tsx
  src/pages/userPage/Menu/Menu.tsx
  src/pages/userPage/personalData/PersonalData.tsx
Labels: Type: Bug, User Profile

#782 Fixed two bugs
  src/App.tsx
  src/components/Notifications/Messages.tsx
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/City/City/City.tsx
  src/pages/Club/Club/Club.tsx
  src/pages/GoverningBody/CreateGoverningBody.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
Labels: Clubs, Governing bodies, Cities (Станиці)

#785 Updated GoverningBodiesTable (covers Bug #2167)
  src/api/governingBodiesApi.tsx
  src/pages/userPage/Secretaries/SecretaryModelForTable.ts
  src/pages/userPage/Secretaries/UserGoverningBodySecretaryTable.tsx
  src/pages/userPage/Secretaries/columnsGoverningBodies.tsx
Labels: Governing bodies, Secretaries ("Діловодства")

#781 Fixed delete on Kadra
  src/components/ButtonCollapse/ButtonCollapse.module.css
  src/components/ButtonCollapse/ButtonCollapse.tsx
  src/pages/DecisionTable/AddDecisionModal.tsx
  src/pages/DecisionTable/DecisionTable.tsx
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/DecisionTable/FormEditDecision.tsx
  src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx
  src/pages/KadraVykhovnykiv/DeleteConfirm.tsx
  src/pages/KadraVykhovnykiv/KVTable.tsx
  src/pages/KadraVykhovnykiv/KadraDropDown.tsx
  src/pages/KadraVykhovnykiv/KadrasPage.tsx
Labels: Senior Staff (Кадра виховників)

#780 Fixed spinner
  src/pages/SignUp/SignUp.tsx
Labels: UI, Terms

#786 Fix validation in edit annual report form
  src/pages/AnnualReport/AnnualReportEdit/AnnualReportEdit.tsx
  src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.tsx
Labels: Type: Bug, AnnualReports

#788 Updated sector table
  src/api/governingBodySectorsApi.tsx
  src/pages/userPage/Secretaries/SectorModelForTable.ts
  src/pages/userPage/Secretaries/UserSectorSecretaryTable.tsx
  src/pages/userPage/Secretaries/columnsSectors.tsx
Labels: Governing bodies, Secretaries ("Діловодства")

#787 User duplication bug fixed
  src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
  src/pages/GoverningBody/CreateGoverningBody.tsx
Labels: Governing bodies

#794 fix search
  src/api/citiesApi.tsx
Labels: Cities (Станиці)

#791 Changed view annual reports due to accesses
  src/components/PrivateLayout/PrivateLayout.tsx
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
Labels: Рівні доступу (Access levels), AnnualReports

#783 fixed bag on edit form
  src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx
  src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
Labels: Precaution, Awards (Відзначення)

#795 add data for edit
  src/pages/City/CreateCity/CreateCity.tsx
Labels: Cities (Станиці)

#789 Only Admin and GoverningBody head can delete user biography/життєпис (Fix #1982)
  src/pages/userPage/Blanks/Blanks.tsx
Labels: Type: Bug, blanks, User Profile

#790 used getPopupContainer property in mentions
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/DecisionTable/FormEditDecision.tsx
Labels: Decisions (Рішення)

#800 fix add to member in CityFollowers
  src/pages/City/City/CityFollowers.tsx
  src/pages/Club/Club/ClubFollowers.tsx
Labels: Cities (Станиці), Hovels (Курені)

#802 add userAccesses
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx
  src/pages/City/City/CityAdministration.tsx
Labels: Cities (Станиці)

#784 UserTableFields reset on cancel, finish and closing ChangeUserModal window
  src/pages/UserTable/ChangeUserRoleForm.tsx
  src/pages/UserTable/ChangeUserRoleModal.tsx
Labels: Type: Bug, User Table

#803 Modified ChangeUserRoleForm (related to Bug#2171)
  src/pages/UserTable/ChangeUserRoleForm.tsx
Labels: Type: Bug, User Table

#797 Users for precautions
  src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
Labels: Precaution

#804 Fixed accesses for viewing annual reports
  src/components/PrivateLayout/PrivateLayout.tsx
  src/models/UserAccess/IUserAccess.ts
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
  src/pages/AnnualReport/AnnualReportTable/CityAnnualReportTable.tsx
  src/pages/AnnualReport/AnnualReportTable/ClubAnnualReport.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/ConfirmedDropdown/ConfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/SavedDropdown/SavedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/Dropdowns/UnconfirmedDropdown/UnconfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/ConfirmedDropdown/ConfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/SavedDropdown/SavedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForClubAnnualReports/UnconfirmedDropdown/UnconfirmedDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/ConfirmedDropdown/ConfirmedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/SavedDropdown/SavedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/DropdownsForRegionReports/UnconfirmedDropdown/UnconfirmedRegionDropdown.tsx
  src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
Labels: Рівні доступу (Access levels), AnnualReports

#801 Returned possibility to change entry date (Fix #1843)
  src/api/activeMembershipApi.ts
  src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
Labels: Type: Bug, Active Membership, User Profile

#807 Fixed viewing annual reports table with two or more roles
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
Labels: Type: Bug, Рівні доступу (Access levels), AnnualReports

#805 Fixed return to previous page bug
  src/pages/City/Cities/ActionCities.tsx
  src/pages/City/Cities/SortedCities.tsx
  src/pages/Club/Clubs/SortedClubs.tsx
  src/pages/Regions/SortedRegions.tsx
Labels: Regions, Clubs, Cities (Станиці), Hovels (Курені)

#806 Fixed bug with editing single Entry date #1843
  src/pages/userPage/ActiveMembership/ActiveMembership.tsx
  src/pages/userPage/ActiveMembership/UserDates/ModalChangeUserDates.tsx
  src/pages/userPage/personalData/PersonalData.tsx
Labels: Type: Bug, Active Membership, User Profile

#809 Added possibility to create announcement from governing body.
  src/pages/GoverningBody/Announcement/Announcement.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/Sector/CreateSector.tsx
Labels: Governing bodies

#799 Kadra edit form
  src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx
Labels: Senior Staff (Кадра виховників)

#810 Fix bug with calendar
  src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
Labels: Awards (Відзначення)

#796 get kadra type id from db
  src/pages/KadraVykhovnykiv/KadrasPage.tsx
Labels: Senior Staff (Кадра виховників)

#811 Recrudescent document upload is now enabled
  src/pages/RegionsBoard/AddDocModal.tsx
Labels: Governing bodies, Regions Board
