Repository ita-social-projects/EPlast-Client, pull requests merged in 2021-05, with the labels that each got.

#355 Fix regular expressions on EditUserPage
  src/pages/userPage/EditUserPage/EditUserPage.tsx
Labels: Type: Bug

#356 Precautions, distinctions, decisions and kadra updates
  src/api/decisionsApi.tsx
  src/api/distinctionApi.tsx
  src/api/precautionApi.tsx
  src/components/NotificationBox/NotificationBox.tsx
  src/components/Notifications/Messages.tsx
  src/pages/DecisionTable/DecisionTable.tsx
  src/pages/DecisionTable/DropDownDecision.tsx
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/DecisionTable/Interfaces/DecisionTableInfo.tsx
  src/pages/DecisionTable/Table.module.css
  src/pages/DecisionTable/columns.tsx
  src/pages/Distinction/DistinctionTable/DistinctionTable.tsx
  src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
  src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx
  src/pages/Distinction/DistinctionTable/Table.module.css
  src/pages/Distinction/DistinctionTable/columns.tsx
  src/pages/Distinction/Interfaces/UserDistinctionTableInfo.tsx
  src/pages/KadraVykhovnykiv/AddNewKadraForm.tsx
  src/pages/KadraVykhovnykiv/KVTable.tsx
  src/pages/KadraVykhovnykiv/KadraDropDown.tsx
  src/pages/KadraVykhovnykiv/KadrasPage.tsx
  src/pages/KadraVykhovnykiv/UpdateKadraForm.tsx
  src/pages/KadraVykhovnykiv/columns.tsx
  src/pages/Precaution/Interfaces/UserPrecauctionTableInfo.tsx
  src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
  src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
  src/pages/Precaution/PrecautionTable/PrecautionTable.tsx
  src/pages/Precaution/PrecautionTable/Table.module.css
  src/pages/Precaution/PrecautionTable/columns.tsx
Labels: Precaution

#359 Edit user page
  src/pages/userPage/Blanks/Blanks.tsx
  src/pages/userPage/EditUserPage/EditUserPage.tsx
Labels: Type: Bug

#360 Member of organization can view profiles users in UserTable
  src/pages/UserTable/DropDownUserTable.tsx
Labels: User Table

#362 Fixed two notifications on hovels
  src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx
Labels: Type: Bug

#363 Fixed wrong space between text fields
  src/pages/userPage/EditUserPage/EditUserPage.module.css
  src/pages/userPage/personalData/PersonalData.less
Labels: Type: Bug

#364 Changed progress bar
  src/pages/userPage/personalData/AvatarAndProgress.tsx
  src/pages/userPage/personalData/AvatarAndProgressStatic.tsx
Labels: Type: Bug

#368 Fixed bug with information on ActiveMembership Page
  src/pages/userPage/ActiveMembership/ActiveMembership.tsx
Labels: Type: Bug

#369 Fix bug with former user
  src/pages/UserTable/ChangeUserRoleForm.tsx
  src/pages/UserTable/ChangeUserRoleModal.tsx
  src/pages/UserTable/ColumnsForUserTable.tsx
  src/pages/UserTable/DropDownUserTable.tsx
Labels: User Table

#370 Added validator to password
  src/pages/ResetPassword/ResetPassword.tsx
Labels: Type: Bug

#377 Add secretary form
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.less
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx
  src/pages/City/City/City.tsx
  src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.less
  src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx
  src/pages/Club/Club/Club.tsx
  src/pages/Regions/AddRegionSecretaryForm.less
  src/pages/Regions/AddRegionSecretaryForm.tsx
  src/pages/Regions/Region.tsx
Labels: Type: Bug

#378 Fixed some bugs
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.less
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx
  src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.less
  src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx
  src/pages/Regions/AddRegionSecretaryForm.less
  src/pages/Regions/AddRegionSecretaryForm.tsx
Labels: Type: Bug

#380 Precautions update & Pdf convertation for Methodic Documents
  src/pages/DecisionTable/DecisionTable.tsx
  src/pages/DecisionTable/DropDownDecision.tsx
  src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx
  src/pages/Documents/DocumentsTable.tsx
  src/pages/Documents/DropDownDocuments.tsx
  src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
  src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
Labels: Precaution
