Repository ita-social-projects/EPlast-Client, pull requests merged in 2022-02, with the labels that each got.

#839 Add message how to create chart on statistics
  src/pages/Statistics/StatisticsCities.less
  src/pages/Statistics/StatisticsCities.tsx
  src/pages/Statistics/StatisticsRegions.less
  src/pages/Statistics/StatisticsRegions.tsx
Labels: Statistics

#840 Updated menu accesses
  src/components/PrivateLayout/PrivateLayout.tsx
Labels: Рівні доступу (Access levels), Menu

#838 Merged 2 components on event page fixed responsiveness
  src/pages/Actions/ActionEvent/EventInfo/EventDetails.less
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
Labels: Events

#841 add notification
  src/api/adminApi.tsx
  src/pages/UserTable/ChangeUserRoleForm.tsx
Labels: User Table

#844 Add validation in creating region annual report
  src/pages/AnnualReport/RegionAnnualReportForm/RegionAnnualReportForm.tsx
Labels: Type: Bug, AnnualReports

#845 Remove numeric input in creating club annual report
  src/pages/AnnualReport/ClubAnnualReportForm/ClubAnnualReportForm.tsx
Labels: Type: Bug, AnnualReports

#842 Fixed target decision validation
  src/api/adminApi.tsx
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/DecisionTable/FormAddDecision.tsx
Labels: Decisions (Рішення)

#852 Fixed #2304
  src/pages/userPage/EditUserPage/EditUserPage.tsx
Labels: Type: Bug, User Profile

#855 Changes in EventCreate file - in Date Picker
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
Labels: Type: Bug, Events
