Repository ita-social-projects/EPlast-Client, pull requests merged in 2022-05, with the labels that each got.

#899 Сoma cannot be placed in the field #2406
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
Labels: Type: Bug, Events

#898 Fixing lopping events requests
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
Labels: Events

#900 Comma input edit event
  src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx
  src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx
  src/pages/Regions/Region.tsx
  src/pages/Regions/RegionFollowers.tsx
Labels: Type: Bug, Events

#894 GoverningBodyAdmin access levels at decisions fix
  src/pages/DecisionTable/DecisionTable.tsx
  src/pages/DecisionTable/DropDownDecision.tsx
Labels: Рівні доступу (Access levels)

#896 Aligning changes fix#2329
  src/pages/City/AddAdministratorModal/AddCitiesSecretaryForm.tsx
  src/pages/Club/AddAdministratorModal/AddClubsSecretaryForm.tsx
  src/pages/GoverningBody/AddAdministratorModal/AddAdministrationModal.less
  src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
  src/pages/GoverningBody/Sector/AddSectorAdminForm.tsx
  src/pages/Regions/AddRegionSecretaryForm.tsx
  src/pages/Regions/Form.module.css
Labels: UI

#893 GoverningBodyAdmin access levels at profile fix
  src/pages/Distinction/DistinctionTable/DistinctionTable.tsx
  src/pages/userPage/ActiveMembership/ActiveMembership.tsx
  src/pages/userPage/EditUserPage/EditUserPage.tsx
  src/pages/userPage/personalData/UserFields.tsx
Labels: Рівні доступу (Access levels)

#901 Empty announcements fixed
  src/pages/GoverningBody/Announcement/AddAnnouncementModal.tsx
  src/pages/GoverningBody/Announcement/Announcement.tsx
  src/pages/GoverningBody/Announcement/EditAnnouncementModal.tsx
  src/pages/GoverningBody/Announcement/FormAddAnnouncement.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/Sector/Sector.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/AddAnnouncementModal.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/EditAnnouncementModal.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/FormAddAnnouncement.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/SectorAnnouncement.tsx
Labels: Type: Bug

#903 User can input active link to the Location field
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
  src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventDetails.less
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.less
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
Labels: Type: Bug, Events

#904 User can input active link to the Location field - update
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.less
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/UserTable/UserTable.tsx
Labels: Type: Bug, Events

#912 When loaded photos are deleted button becomes disabled
  src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx
Labels: Type: Bug, Events

#914 Change align sorting arrows #1459
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.less
  src/pages/UserTable/ColumnsForUserTable.tsx
Labels: Type: Bug, User Table, UI

#905 Fixing bug 2405
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
Labels: Type: Bug, Events

#907 Fix bug 2143
  src/api/NotificationBoxApi.tsx
Labels: Events

#919 Statistics are created based only on Approved Requests (#2131)
  src/api/NotificationBoxApi.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventDetails.less
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.less
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/FormAddPictures.tsx
  src/pages/Actions/ActionEvent/EventInfo/SortedEventInfo.tsx
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.less
  src/pages/Statistics/StatisticsRegions.tsx
  src/pages/UserTable/ColumnsForUserTable.tsx
Labels: enhancement, Statistics

#892 fix main bug
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
Labels: User Profile

#921 Popup notification
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Statistics/StatisticsCities.tsx
  src/pages/Statistics/StatisticsRegions.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
Labels: Type: Bug, Events

#931 fixed bug 2408 and 2300 fixed mistake
  src/pages/Club/Club/Club.tsx
Labels: Hovels (Курені)

#932 fix problem with validator on disabled date
  src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx
Labels: Type: Bug, Events

#917 Fix issue 2389
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
Labels: Type: Enhancement, Governing bodies

#922 Fix GBAdmin not being able to create city
  src/pages/City/Cities/SortedCities.tsx
Labels: Cities (Станиці)

#915 fixed annual report button, bug#2292
  src/pages/AnnualReport/AnnualReportTable/RegionAnnualReportTable.tsx
Labels: Type: Bug, AnnualReports

#920 Only form statistics based on approved reports
  src/components/Notifications/Messages.tsx
  src/pages/Statistics/StatisticsCities.tsx
  src/pages/Statistics/StatisticsRegions.tsx
Labels: enhancement, Status: In Progress, Statistics

#933 Fix CreateCity form not having data
  src/pages/City/CreateCity/CreateCity.tsx
Labels: Type: Bug, City

#935 Statistics table fix and total column
  src/pages/Statistics/StatisticsCities.tsx
  src/pages/Statistics/StatisticsRegions.tsx
Labels: enhancement, Statistics
