Repository ita-social-projects/EPlast-Client, pull requests merged in 2022-03, with the labels that each got.

#851 Fixed #2334 #2159 #2344
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.less
  src/pages/AnnualReport/AnnualReportForm/AnnualReportForm.tsx
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
Labels: Type: Bug, AnnualReports

#857 Fixed validation decision description
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
  src/pages/DecisionTable/FormAddDecision.tsx
  src/pages/Documents/FormAddDocument.tsx
  src/pages/KadraVykhovnykiv/KVTable.tsx
  src/pages/KadraVykhovnykiv/KadrasPage.tsx
  src/pages/UserTable/ChangeUserRoleForm.tsx
Labels: Decisions (Рішення)

#863 Event create alternate
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
  src/pages/Documents/FormAddDocument.tsx
Labels: Type: Bug, Events

#864 Datepicker
  src/pages/Distinction/DistinctionTable/AddDistinctionModal.tsx
  src/pages/Distinction/DistinctionTable/DeleteTypeConfirm.tsx
  src/pages/Distinction/DistinctionTable/DistinctionTable.tsx
  src/pages/Distinction/DistinctionTable/EditDistinctionTypesModal.tsx
  src/pages/Distinction/DistinctionTable/Form.module.css
  src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
  src/pages/Distinction/DistinctionTable/FormEditDistinction.tsx
  src/pages/Distinction/DistinctionTable/FormEditDistinctionTypes.tsx
  src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
  src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
Labels: Precaution, Awards (Відзначення)

#862 add options to filter
  src/pages/UserTable/ColumnsForUserTable.tsx
Labels: User Table

#853 Governing body bugs Fixed #2268
  src/api/UserApi.tsx
  src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/Sector/Sector.tsx
Labels: Type: Bug, Regions Board

#868 No more required questions while creating event; Changed "x" on "-" in event form
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/Actions/ActionEvent/EventCreate/EventCreate.tsx
  src/pages/Actions/ActionEvent/EventCreate/EventCreateDrawer.tsx
  src/pages/UserTable/ColumnsForUserTable.tsx
Labels: Type: Bug, Events

#865 City Admin can assign any degree to members
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
Labels: Active Membership

#872 Fix bug #2143 with buttons
  src/pages/Actions/ActionEvent/EventCard/EventCard.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
Labels: Type: Bug, Events

#873 Added email
  src/pages/Distinction/DistinctionTable/AddDistinctionModal.tsx
  src/pages/Distinction/DistinctionTable/EditDistinctionTypesModal.tsx
  src/pages/Distinction/DistinctionTable/Form.module.css
  src/pages/Distinction/DistinctionTable/FormAddDistinction.tsx
Labels: Precaution, Awards (Відзначення)

#866 Governing bodies admin add select fix and upgrade
  src/api/adminApi.tsx
  src/models/UserTable/ShortUserInfo.tsx
  src/pages/GoverningBody/AddAdministratorModal/AddGoverningBodiesSecretaryForm.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/Sector/AddSectorAdminForm.tsx
  src/pages/GoverningBody/Sector/Sector.tsx
  src/pages/Regions/Form.module.css
Labels: Type: Bug, Governing bodies

#875 Fixes of event editing form
  src/api/regionsApi.tsx
  src/pages/Actions/ActionEvent/EventCreate/EventCreateDrawer.tsx
  src/pages/Actions/ActionEvent/EventEdit/EventEdit.tsx
  src/pages/Actions/ActionEvent/EventEdit/EventEditDrawer.tsx
  src/pages/Regions/RegionAdministration.tsx
Labels: Type: Bug, Events

#877 Changed calling of two date fields #2122
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
Labels: Type: Bug, Events
