Repository ita-social-projects/EPlast-Client, pull requests merged in 2022-06, with the labels that each got.

#937 Fix issue #2479
  src/pages/GoverningBody/GoverningBody/GoverningBody.less
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/Sector/Sector.tsx
Labels: Governing bodies

#928 Pin announcements
  src/api/announcementsApi.ts
  src/api/governingBodiesApi.tsx
  src/api/governingBodySectorsApi.tsx
  src/models/GoverningBody/Announcement/Announcement.tsx
  src/models/GoverningBody/GoverningBodyAnnouncement.tsx
  src/pages/GoverningBody/Announcement/AddAnnouncementModal.tsx
  src/pages/GoverningBody/Announcement/Announcement.module.css
  src/pages/GoverningBody/Announcement/Announcement.tsx
  src/pages/GoverningBody/Announcement/DeleteConfirm.tsx
  src/pages/GoverningBody/Announcement/EditAnnouncementModal.tsx
  src/pages/GoverningBody/Announcement/FormAddAnnouncement.tsx
  src/pages/GoverningBody/Announcement/PicturesWallModal.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/Sector/Sector.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/AddAnnouncementModal.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/EditAnnouncementModal.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/FormAddAnnouncement.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/SectorAnnouncement.tsx
Labels: Governing bodies

#940 Bug/#2300 add fix
  src/pages/Club/AddAdministratorModal/AddAdministratorModal.tsx
Labels: User Table, Hovels (Курені)

#934 legislation security
  src/pages/Documents/AddDocumetsModal.tsx
  src/pages/Documents/DocumentsTable.tsx
  src/pages/Documents/DropDownDocuments.tsx
  src/pages/Documents/FormAddDocument.tsx
Labels: Legislation [Репозитарій], Рівні доступу (Access levels)

#943 Event notification fix - moved logic to backend #2411
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
Labels: Type: Bug, Events

#944 Fix issue #2216
  src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx
Labels: Type: Bug, Cities (Станиці)

#950 Fix issue #2503
  src/components/Quill/FormWithQuill.css
  src/pages/AnnouncementsTable/Forms/FormEditAnnouncement.tsx
Labels: Governing bodies

#951 Fix issue #1481
  src/components/Header/HeaderContainer.tsx
Labels: UI

#954 Fix issue #2542
  src/pages/AnnouncementsTable/Forms/FormAddAnnouncement.tsx
Labels: Type: Bug

#953 Fix issue #2216
  src/pages/City/AddAdministratorModal/AddAdministratorModal.tsx
Labels: UI

#955 deleted Decisions from RegionsBoard
  src/pages/RegionsBoard/RegionBoard.tsx
Labels: Regions Board

#957 Reverse year order
  src/pages/Statistics/StatisticsCities.tsx
  src/pages/Statistics/StatisticsRegions.tsx
Labels: enhancement, Statistics

#959 Updated announcements view (pined status)
  src/pages/GoverningBody/Announcement/Announcement.tsx
  src/pages/GoverningBody/Announcement/DropDownAnnouncement.tsx
  src/pages/GoverningBody/GoverningBody/GoverningBody.tsx
  src/pages/GoverningBody/Sector/Sector.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/DeleteConfirm.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/DropDownAnnouncement.tsx
  src/pages/GoverningBody/Sector/SectorAnnouncement/SectorAnnouncement.tsx
Labels: UI

#961 At User Table on tab "Зацікавлені" correct users now
  src/pages/UserTable/UserTable.tsx
Labels: User Table

#945 Remove required rule from office number
  src/models/GllobalValidations/DescriptionValidation.tsx
Labels: Cities (Станиці)

#952 Checkbox for participants
  src/api/eventsApi.ts
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
Labels: Type: Bug, Events

#963 Modal for followers with fixed degrees
  src/pages/City/City/City.tsx
  src/pages/City/City/CityFollowers.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
Labels: Type: Bug, Cities (Станиці)

#964 Accept User To City Form On User Table
  src/models/UserTable/DropdownFunc.tsx
  src/pages/City/City/City.tsx
  src/pages/UserTable/AcceptUserToCityForm.tsx
  src/pages/UserTable/AcceptUserToCityModal.tsx
  src/pages/UserTable/DropDownUserTable.tsx
  src/pages/UserTable/DropdownItem.tsx
  src/pages/UserTable/UserTable.tsx
Labels: User Table

#966 modified modal title
  src/pages/City/City/City.tsx
  src/pages/City/City/CityFollowers.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/ModalAddPlastDegree.tsx
Labels: Type: Bug, Cities (Станиці)

#971 Fixing searching bug on Regions, Cities and Clubs 2299
  src/pages/City/Cities/SortedCities.tsx
  src/pages/Club/Clubs/SortedClubs.tsx
  src/pages/Regions/SortedRegions.tsx
Labels: Regions, Clubs, Cities (Станиці)

#970 Add user table link to Club page for admins
  src/pages/City/City/City.tsx
  src/pages/Club/Club/Club.tsx
Labels: Clubs

#973 Fixed buttons aligning #2515
  src/pages/Club/AddAdministratorModal/AddAdministrationModal.less
  src/pages/UserTable/ChangeUserRoleModal.less
  src/pages/UserTable/ChangeUserRoleModal.tsx
Labels: Type: Bug, User Table

#967 Precaution store
  src/pages/Precaution/PrecautionTable/AddPrecautionModal.tsx
  src/pages/Precaution/PrecautionTable/DeleteConfirm.tsx
  src/pages/Precaution/PrecautionTable/DropDownPrecautionTable.tsx
  src/pages/Precaution/PrecautionTable/EditPrecautionModal.tsx
  src/pages/Precaution/PrecautionTable/EditPrecautionTypesModal.tsx
  src/pages/Precaution/PrecautionTable/FormAddPrecaution.tsx
  src/pages/Precaution/PrecautionTable/FormEditPrecaution.tsx
  src/pages/Precaution/PrecautionTable/FormEditPrecautionTypes.tsx
  src/pages/Precaution/PrecautionTable/PrecautionTable.tsx
  src/stores/StorePrecaution.tsx
Labels: Precaution

#968 Citieslevel
  src/pages/City/CreateCity/CreateCity.tsx
Labels: Cities (Станиці)

#969 Fix for website freeze when email is validated
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/City/CreateCity/CreateCity.tsx
Labels: Regions, Cities (Станиці)

#974 Region city club validation fix and URL validation
  src/components/Notifications/Messages.tsx
  src/models/GllobalValidations/DescriptionValidation.tsx
  src/pages/City/CreateCity/CreateCity.tsx
  src/pages/Club/CreateClub/CreateClub.tsx
  src/pages/Regions/AddRegion.tsx
  src/pages/Regions/RegionEdit.tsx
Labels: Type: Bug, Regions, Clubs, Cities (Станиці)

#962 Governing body admin user table fix
  src/pages/RegionsBoard/AddMainAdministratorModal/AddRegionBoardMainAdminForm.tsx
  src/pages/RegionsBoard/AddMainAdministratorModal/AddRegionBoardMainAdminModal.tsx
  src/pages/RegionsBoard/RegionBoard.tsx
  src/pages/UserTable/ChangeUserGoverningBodyForm.tsx
  src/pages/UserTable/DropdownItem.tsx
Labels: User Table

#975 City user fix - spinner, loading user and his photo
  src/pages/City/City/City.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
Labels: Type: Bug, City

#976 Changed arrows aligning on user table
  src/pages/UserTable/ColumnsForUserTable.tsx
Labels: Type: Bug, City

#977 Update UserTable tab sorting
  src/pages/UserTable/UserTable.tsx
Labels: User Table

#978 Fix issue #2012
  src/pages/Regions/RegionAdministration.tsx
Labels: User Table, Regions, Region

#979 Refactoring - replace country with region naming
  src/components/PrivateLayout/PrivateLayout.tsx
  src/pages/AnnualReport/AnnualReportTable/AnnualReportTable.tsx
  src/pages/Regions/Region.tsx
Labels: Type: Bug, City, Code refactoring

#984 Delete accept to city item, instead here is 'Додати до уладу' and partial fix #2561
  src/models/UserTable/DropdownFunc.tsx
  src/pages/UserTable/DropDownUserTable.tsx
  src/pages/UserTable/DropdownItem.tsx
  src/pages/userPage/ActiveMembership/PlastDegree/FormAddPlastDegree.tsx
Labels: Type: Bug, User Table
