Repository ita-social-projects/EPlast-Client, pull requests merged in 2022-04, with the labels that each got.

#878 Clicked button turns disabled without ability to be pressed again - bug #2246
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.less
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
Labels: Type: Bug, Events

#880 [Regional Board of the Plast/City/Hovel/Region] aligning changes after entering an empty spaces #2329
  src/pages/City/AddDocumentModal/AddDocumentModal.tsx
  src/pages/Club/AddDocumentModal/AddDocumentModal.tsx
  src/pages/GoverningBody/AddDocumentModal/AddDocumentModal.tsx
  src/pages/GoverningBody/Sector/AddDocumentModal.tsx
  src/pages/Regions/Form.module.css
  src/pages/RegionsBoard/AddDocModal.tsx
Labels: Type: Bug, Regions, City, Clubs, UI, Hovels (Курені)

#885 modificated styles for buttons
  src/pages/Actions/ActionEvent/EventUser/EventUser.module.css
  src/pages/Actions/ActionEvent/EventUser/EventUser.tsx
Labels: Type: Bug, Events

#888 Bug 1256
  src/pages/Actions/ActionEvent/EventInfo/EventDetailsHeader.tsx
  src/pages/Actions/ActionEvent/EventInfo/EventInfo.tsx
  src/pages/Actions/ActionEvent/EventInfo/ParticipantsTable.tsx
Labels: Type: Bug, Events

#889 Buttons in modal
  src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.module.css
  src/pages/Actions/ActionEvent/EventCalendar/EventCalendar.tsx
Labels: Type: Bug, Events

#890 change access kurinhead
  src/pages/userPage/ActiveMembership/ActiveMembership.tsx
Labels: Рівні доступу (Access levels), User Profile

#887 Organization admin(GoverningBodyAdmin) added items to DropDown in UserTable
  src/api/governingBodiesApi.tsx
  src/models/Roles/AdminRole.tsx
  src/models/Roles/Roles.tsx
  src/models/UserTable/DropdownFunc.tsx
  src/pages/UserTable/ChangeUserGoverningBodyForm.tsx
  src/pages/UserTable/ChangeUserGoverningBodyModal.tsx
  src/pages/UserTable/DeleteGoverningBodyAdminForm.tsx
  src/pages/UserTable/DeleteGoverningBodyAdminModal.tsx
  src/pages/UserTable/DropDownUserTable.tsx
  src/pages/UserTable/DropdownItem.tsx
  src/pages/UserTable/UserTable.tsx
Labels: User Table, Governing bodies, UI, Рівні доступу (Access levels)
